services:
  nextjs:
    build: ./frontend
    ports:
      - "3000:3000"
  express:
    build: ./backend
    ports:
      - "3004:3004"
    env_file:
      - .env
  mysql:
    image: mysql:5.7 # Välj en MySQL-version
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banksite_db
    ports:
      - "8890:8889" # Porten som MySQL-servern lyssnar på (MAMP)
    volumes:
      - mysql-data:/var/lib/mysql-docker

volumes:
  mysql-data:
